[workspace]
resolver = "3"
members = ["crates/hmcl-core", "crates/hmcl-ui", "crates/hmcl"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
authors = ["hmcl-rs contributors"]

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
oxideav-png = "0.1"
zip = "2"
dirs = "6"
sys-locale = "0.3"
dark-light = "2"
webbrowser = "1"
lyon = "1"
eframe = "0.32"
egui = "0.32"
egui_extras = { version = "0.32", features = ["image"] }
hmcl-core = { path = "crates/hmcl-core" }
hmcl-ui = { path = "crates/hmcl-ui" }

[profile.release]
opt-level = 2
lto = "thin"
